# Generated by Django 3.2.8 on 2021-10-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=50, verbose_name='Hash field')),
                ('name', models.CharField(max_length=250, verbose_name='Company name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone number')),
                ('founder', models.CharField(max_length=200, verbose_name='Founder of company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=50, verbose_name='Hash field')),
                ('name', models.CharField(max_length=250, verbose_name='Store name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone number')),
                ('address', models.CharField(max_length=300, verbose_name='Store address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=50, verbose_name='Hash field')),
                ('product_title', models.CharField(max_length=250, verbose_name='Product title')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='Product count')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='store.consumer')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
